// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oukydhqxyrgawnvxwfis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91a3lkaHF4eXJnYXdudnh3ZmlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTMzNzAsImV4cCI6MjA2MjM2OTM3MH0.vMaZ8hWHaJ5v1qXsF7EAIBT_XN8FoAOLEPlvYQXxMsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);